import = ["~/.config/alacritty/themes/cool  alacritty.toml
  
[env]
TERM = "xterm-256color"
  
[window]
padding.x = 20
padding.y = 25
decorations = "Buttonless"
   
opacity = 0.65
blur = true
   
option_as_alt = "Both"
   
[font]
normal.family = "MesloLGS Nerd Font Mono"
   
size = 15
